apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-fib
  namespace: test
spec:
  selector:
    matchLabels:
      app: go-fib
  replicas: 2
  template:
    metadata:
      labels:
        app: go-fib
    spec:
      containers:
      - name: go-fib
        image: thiagodevel/go-fib:0.0.1
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: go-fib
  namespace: test
  labels:
    app: go-fib
spec:
  type: NodePort
  ports:
  - port: 8000
  selector:
    app: go-fib      